package core.classes;

/**
 * Extends Part class.
 *
 *
 */

public class InHouse extends Part{
    private int machineId;

    /**
     *
     * @param id int value
     * @param name string value
     * @param price double value
     * @param stock int value
     * @param min int value
     * @param max int value
     * @param machineId int autogenerated.
     */
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineId) {
     super(id, name, price, stock, min, max);
     this.machineId = machineId;
    }

    /**
     *
     * @param id Id to set.
     */
    public void setMachinedId(int id){
        this.machineId = id;
    }

    /**
     *
     * @return int The machine Id.
     */
    public int getMachinedId (){
        return this.machineId;
    }

}
