package core.classes;

/**
 * Extends Part class.
 * Part That is made by the company has a machine Id instead of company name.
 *
 * RUNTIME ERROR: Location: constructor.  Error when trying to create a new instance.
 * I forgot to call super and pass params.
 *
 * FUTURE IMPROVEMENT: Add more details about the part. add a list of products its associated with,
 * so that if it was deleted, it could be removed from them as well.
 *
 */

public class InHouse extends Part{
    private int machineId;

    /**
     *
     * @param id int value
     * @param name string value
     * @param price double value
     * @param stock int value
     * @param min int value
     * @param max int value
     * @param machineId int autogenerated.
     */
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineId) {
     super(id, name, price, stock, min, max);
     this.machineId = machineId;
    }

    /**
     *
     * @param id Id to set.
     */
    public void setMachinedId(int id){
        this.machineId = id;
    }

    /**
     *
     * @return int The machine Id.
     */
    public int getMachinedId (){
        return this.machineId;
    }

}
